"""add unique constraints

Revision ID: 6e8397e51f37
Revises: ceee8dc52ca1
Create Date: 2024-09-23 14:55:56.111084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e8397e51f37'
down_revision: Union[str, None] = 'ceee8dc52ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_budget_category', 'category', ['budget_id', 'name'])
    op.create_unique_constraint(None, 'predefinedcategory', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predefinedcategory', type_='unique')
    op.drop_constraint('uq_budget_category', 'category', type_='unique')
    # ### end Alembic commands ###
