"""fix transaction

Revision ID: 1549c7102341
Revises: 6e8397e51f37
Create Date: 2024-09-28 14:56:17.513871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1549c7102341'
down_revision: Union[str, None] = '6e8397e51f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_column('transaction', 'money')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('money', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('transaction', 'amount')
    # ### end Alembic commands ###
