"""stock models

Revision ID: 9b7ed4735af3
Revises: 58a364e34185
Create Date: 2024-12-08 14:27:54.962341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b7ed4735af3'
down_revision: Union[str, None] = '58a364e34185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockaccount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounttransaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_performed', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DIVIDENDS', 'DEPOSIT', 'WITHDRAWAL', name='accounttransactiontype'), nullable=False),
    sa.Column('paid_fee', sa.Float(), nullable=False),
    sa.Column('taxes_to_pay', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['stockaccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockposition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('count_active', sa.Integer(), nullable=False),
    sa.Column('date_opened', sa.Date(), nullable=False),
    sa.Column('dividends_payed', sa.Float(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['stockaccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocktransaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_performed', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='stocktransactiontype'), nullable=False),
    sa.Column('paid_fee', sa.Float(), nullable=False),
    sa.Column('taxes_to_pay', sa.Float(), nullable=False),
    sa.Column('stock_position_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['stockaccount.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_position_id'], ['stockposition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocktransaction')
    op.drop_table('stockposition')
    op.drop_table('accounttransaction')
    op.drop_table('stockaccount')
    # ### end Alembic commands ###
