"""stocks datetime

Revision ID: b3735416851c
Revises: 1fa118300e1d
Create Date: 2025-02-23 15:41:47.029291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3735416851c'
down_revision: Union[str, None] = '1fa118300e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounttransaction', sa.Column('datetime_performed', sa.DateTime(), nullable=False))
    op.drop_column('accounttransaction', 'date_performed')
    op.add_column('stockposition', sa.Column('datetime_opened', sa.DateTime(), nullable=False))
    op.drop_column('stockposition', 'date_opened')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockposition', sa.Column('date_opened', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('stockposition', 'datetime_opened')
    op.add_column('accounttransaction', sa.Column('date_performed', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('accounttransaction', 'datetime_performed')
    # ### end Alembic commands ###
