"""stock symbols

Revision ID: 2f2a29b24169
Revises: b3735416851c
Create Date: 2025-03-10 16:41:13.462554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f2a29b24169'
down_revision: Union[str, None] = 'b3735416851c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocksymbols',
    sa.Column('figi', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('exchange_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.PrimaryKeyConstraint('figi')
    )
    op.create_index(op.f('ix_stocksymbols_symbol'), 'stocksymbols', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocksymbols_symbol'), table_name='stocksymbols')
    op.drop_table('stocksymbols')
    # ### end Alembic commands ###
