"""stock symbols

Revision ID: 5afe071b6c71
Revises: b3735416851c
Create Date: 2025-04-03 20:49:54.293465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5afe071b6c71'
down_revision: Union[str, None] = 'b3735416851c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocksymbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('figi', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('exchange_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('figi'),
    sa.UniqueConstraint('symbol', 'exchange_code', name='uq_symbol_exchange_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocksymbol')
    # ### end Alembic commands ###
