"""audit log

Revision ID: 252b593b51ad
Revises: 0e582d6dc4ff
Create Date: 2025-04-10 18:55:24.493517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '252b593b51ad'
down_revision: Union[str, None] = '0e582d6dc4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create function which will run on trigger
    op.execute("""
    CREATE OR REPLACE FUNCTION log_transaction_changes()
    RETURNS TRIGGER AS $$
    BEGIN
        IF (TG_OP = 'INSERT') THEN
            INSERT INTO auditlog(table_name, operation, record_id, new_data)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, to_jsonb(NEW));
            RETURN NEW;

        ELSIF (TG_OP = 'UPDATE') THEN
            INSERT INTO auditlog(table_name, operation, record_id, old_data, new_data)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, to_jsonb(OLD), to_jsonb(NEW));
            RETURN NEW;

        ELSIF (TG_OP = 'DELETE') THEN
            INSERT INTO auditlog(table_name, operation, record_id, old_data)
            VALUES (TG_TABLE_NAME, TG_OP, OLD.id, to_jsonb(OLD));
            RETURN OLD;
        END IF;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)
    # create trigger for transaction
    op.execute("""
    CREATE TRIGGER trigger_transaction_audit
    AFTER INSERT OR UPDATE OR DELETE ON transaction
    FOR EACH ROW
    EXECUTE FUNCTION log_transaction_changes();
    """)
    # create trigger for accounttransaction
    op.execute("""
    CREATE TRIGGER trigger_account_transaction_audit
    AFTER INSERT OR UPDATE OR DELETE ON accounttransaction
    FOR EACH ROW
    EXECUTE FUNCTION log_transaction_changes();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trigger_transaction_audit ON transaction;")
    op.execute("DROP TRIGGER IF EXISTS trigger_account_transaction_audit ON accounttransaction;")
    op.execute("DROP FUNCTION IF EXISTS log_transaction_changes();")
    # ### end Alembic commands ###
