"""use decimal

Revision ID: 01b61b569df5
Revises: 6254a03a6438
Create Date: 2025-04-17 15:51:39.733952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01b61b569df5'
down_revision: Union[str, None] = '6254a03a6438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounttransaction', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    op.alter_column('accounttransaction', 'paid_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    op.alter_column('accounttransaction', 'taxes_to_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    op.alter_column('accounttransaction', 'price_per_item',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    op.alter_column('budget', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    op.alter_column('category', 'category_restriction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    op.alter_column('stockaccount', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    op.alter_column('stockposition', 'price_per_stock_in',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    op.alter_column('transaction', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'amount',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('stockposition', 'price_per_stock_in',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('stockaccount', 'balance',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('category', 'category_restriction',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('budget', 'balance',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('accounttransaction', 'price_per_item',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('accounttransaction', 'taxes_to_pay',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('accounttransaction', 'paid_fee',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('accounttransaction', 'total_amount',
               existing_type=sa.Numeric(scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
