repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=700']
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
    -   id: ruff
        args: ["--fix"]
    -   id: ruff-format
