services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15.8
    ports:
      - "8001:5432"
    env_file: ".env"
    container_name: db
