[tool.ruff]
line-length = 120
src = ["app"]
exclude = ["app/migrations/versions/*"]

[tool.ruff.lint]
ignore = ["F401", "D104", "D100", "D107", "D203", "D213"]
select = ["I", "D", "E4", "E7", "E9", "F"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.pydocstyle]
ignore-decorators = ["property"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["D103"]

[tool.mypy]
strict = true
disallow_subclassing_any = false
disallow_untyped_decorators = false

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
filterwarnings = ["ignore::DeprecationWarning:passlib.utils", "ignore::DeprecationWarning:pytest_asyncio.plugin"]
