[tool.ruff]
line-length = 120
src = ["app"]

[tool.ruff.lint]
ignore = ["F401", "D104", "D100", "D107", "D203", "D213"]
select = ["I", "D", "E4", "E7", "E9", "F"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.pydocstyle]
ignore-decorators = ["property"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.mypy]
mypy_path = "app"
